name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Add .nojekyll
        run: touch ./build/.nojekyll
      - name: Add CNAME
        run: echo weitz.contact >> ./build/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
